import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/lib/fonts";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <AuthProvider>
          {children}

        </AuthProvider>
      </body>
    </html>
  );
}
